#server.port=8888
#spring.cloud.config.server.git.uri=https://gitlab-gl.stackroute.in/gl-fsd-wave5/brainzo/-/tree/v1.0.0/config-server


server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brainz-github/brainzo-config-repo
          # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
#        native:
#          searchLocations: file:///${GIT_REPO}